### ISSUE TITLE
issue while building from sourcef

### ISSUE THREAD

**Issue by Sleepycoderlol** [KraXen72/crankshaft#13]
when i built the client from source everything was working fine but the settings tab was not working.
When i click on client settings.. tab it shows no settings...

Thankyou

**Comment by KraXen72** [comment]
yes, they are currently broken. wait for fix or pr.

**Comment by Sleepycoderlol** [comment]
Ok :))

**Comment by KraXen72** [comment]
it's fixed in the latest commits. feel free to pull & build again. official release when i finalize/stabilize things
