### ISSUE TITLE
signing in

### ISSUE THREAD

**Issue by moongazer07** [KraXen72/crankshaft#25]
how to stay logged in so you don't have to keep entering password especially if its a complex one

**Comment by by43673** [comment]
You should be logged in by default if you login once.

**Comment by KraXen72** [comment]
you can try clearing the appdata/roaming/crankshaft folder (back up your crankshaft config first just in case), or reinstalling. some users had problems with this but generally there's no reason crankshaft should log you out, and it stays logged in by default

**Comment by moongazer07** [comment]
> you can try clearing the appdata/roaming/crankshaft folder (back up your crankshaft config first just in case), or reinstalling. some users had problems with this but generally there's no reason crankshaft should log you out, and it stays logged in by default

it does not stay logged in
