### ISSUE TITLE
optimise ideas

### ISSUE THREAD

**Issue by moongazer07** [KraXen72/crankshaft#27]
what about compiling to wasm or using [v8-compile-cache](https://github.com/zertosh/v8-compile-cache)

**Comment by paintingofblue** [comment]
doesn't v8-compile-cache only speed up the start time of the app (impact it has for electron apps is negligible) & can nodejs apps even be compiled to wasm

**Comment by asger-finding** [comment]
Project code is already bundled to asar, and wasm still needs JavaScript to interact with the page. There's no practical application for either in cranskhaft (or any other typical Krunker client)
