### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by ihyfave** [KraXen72/crankshaft#28]
At certain times of  dying in the game, my game freezes. It freezes on the death zoom in after i die. Any suggestions on how to fix?

**Comment by paintingofblue** [comment]
do you have any userscripts enabled and are you on the latest version / are you using a nightly release

also, do any errors show up in inspect element when this happens

**Comment by ihyfave** [comment]
All the user scripts are off, i don't know if i'm on the current release, and also how do you check inspect element on the client.

**Comment by ihyfave** [comment]
I get a lot of errors in the console.

**Comment by paintingofblue** [comment]
> I get a lot of errors in the console. 

can you screenshot them then please?

**Comment by ihyfave** [comment]
sure

**Comment by ihyfave** [comment]
![Screenshot (3)](https://github.com/KraXen72/crankshaft/assets/125415238/ff63f4b9-b28f-4ee9-bc7b-bd6baf60134a)

**Comment by paintingofblue** [comment]
the only error of significance is the webgl errors, the rest are entirely unrelated. are you able to screenshot the flags that you have enabled in settings? would you also be able to experiment with having all of them off, and trying to isolate the issue by enabling them one by one? it's most likely one of the flags that are causing the issue

**Comment by ihyfave** [comment]
![Screenshot (4)](https://github.com/KraXen72/crankshaft/assets/125415238/8c197c84-5c52-431e-866e-cfd32e46eb42)

**Comment by paintingofblue** [comment]
> would you also be able to experiment with having all of them off, and trying to isolate the issue by enabling them one by one? it's most likely one of the flags that are causing the issue

**Comment by ihyfave** [comment]
i was just playing some games and it was still doing it. Also i found the error that made the game freeze.
![Screenshot (5)](https://github.com/KraXen72/crankshaft/assets/125415238/923b3674-6288-4d3c-9a37-9d1a366af730)

**Comment by paintingofblue** [comment]
so to confirm, you've tested with flags disabled? does it still freeze? also you sent a full page screenshot so we can't see what error you think causes it lol

**Comment by ihyfave** [comment]
I tested it disabled and it was still freezing that was the screen shot. Do i need to crop it, the webGL error 
![Screenshot 2023-11-22 214959](https://github.com/KraXen72/crankshaft/assets/125415238/2071af52-dae2-41c6-9777-98c759a5110b)

**Comment by paintingofblue** [comment]
yes that was what i thought it was, are you able to join the discord so i can help you better? replying on github issues is a little hard. ping wa#3750 in the support channel once you join and we can go from there

**Comment by ihyfave** [comment]
gotchu
