### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by floppykr** [KraXen72/crankshaft#7]
sometimes after i close the client, it stays open in the background in my task manager. Normally, i don't notice until the process starts taking up 10+ GB of my ram. this was an issue i also had with idkr, but never with other clients like Null or Client++. i really like crankshaft, but i really do not want to have to open my task manager every time i close the client.

**Comment by floppykr** [comment]
on windows full 64 bit version btw

**Comment by asger-finding** [comment]
```typescript
app.on('quit', () => app.quit());
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') return app.quit();
	return null;
});
```
Using this personally.

**Comment by KraXen72** [comment]
added this. maybe it was because i was using the ungraceful app.exit()
