### ISSUE TITLE
GPU process isn't usable. Goodbye. [Linux]

### ISSUE THREAD

**Issue by bytooo** [KraXen72/crankshaft#9]
I get the following error when I try to run the appimage on linux:

```
[9327:1014/141202.412653:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    9327 trace trap (core dumped)
```

System Info:
OS: Arch Linux
Desktop: i3wm
Kernel: 6.0.1-arch1-1
CPU: Intel i5-8400
GPU: NVIDIA GeForce GTX 1060 3GB

**Comment by Mixaz017** [comment]
This is a known Electron issue that got fixed in later versions but a lot of Krunker clients stay on older versions due to newer versions having much worse performance. A workaround is to launch the client with `--no-sandbox` flag.

**Comment by Im-Kal** [comment]
Yes, I had this exact issue. I just used the above flag and it works 👍 

Also create a .desktop shortcut with the above flag in the launch params to make it easier.

**Comment by bytooo** [comment]
Tysm!
